"""initial

Revision ID: c0ad4dce7755
Revises: 
Create Date: 2026-01-27 18:04:15.667823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ad4dce7755'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('board_categories_board_id_fkey'), 'board_categories', type_='foreignkey')
    op.create_foreign_key(None, 'board_categories', 'boards', ['board_id'], ['id'])
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'])
    op.drop_constraint(op.f('post_likes_post_id_fkey'), 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(op.f('posts_category_id_fkey'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('posts_board_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'board_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_board_id_fkey'), 'posts', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('posts_category_id_fkey'), 'posts', 'board_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key(op.f('post_likes_post_id_fkey'), 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'board_categories', type_='foreignkey')
    op.create_foreign_key(op.f('board_categories_board_id_fkey'), 'board_categories', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
