"""auto_dev_20260128_205648

Revision ID: f13f189e3c1a
Revises: c0ad4dce7755
Create Date: 2026-01-28 20:56:49.133467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13f189e3c1a'
down_revision: Union[str, Sequence[str], None] = 'c0ad4dce7755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
